### ISSUE TITLE
Threadedness Tool does not add Braid-to-Braid Nodes field to Network

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#59] opened 2017-12-04 23:25 UTC
Was just reviewing my data and realized that I had never encountered a watershed where there been a NODES_BB field added to the segmented network to count number of Braid-to-Braid nodes. I thought this was because there were no BB nodes, but in the case of Lower Yakima, I found BB nodes present in the Nodes output but no NODES_BB field was added to the Segmented Network. I'm guessing this issue goes back to the original versions of the tool. Attached is the data:

[Thread_BBNode_Issue.zip](https://github.com/Riverscapes/arcGNAT/files/1529137/Thread_BBNode_Issue.zip)

**Comment by jesselangdon** [comment] 2017-12-08 01:46
This is by design, so closing this issue.

**Closed by jesselangdon** 2017-12-08 01:46 UTC
